### ISSUE TITLE
Illegal instruction while importing custom tensorflow

### ISSUE THREAD

**Issue by youben11** [tf-encrypted/tf-seal#48]
The environment is the tf-seal docker image that I have made available [here](https://cloud.docker.com/u/youben/repository/docker/youben/tf-seal).

So when I run the container on [play-with-docker](https://labs.play-with-docker.com/) tf_seal is working just fine then when I run the container on my local machine I get an `Illegal instruction` error. The image is the same on both machine and not different builds. Both machines are running an x86_64 processor.

Below is a full backtrace from the python interpreter while importing tensorflow.

```bash
(gdb) backtrace 
#0  0x00007f19c9e139bf in tensorflow::UnaryVariantOpRegistry::RegisterDeviceCopyFn(tensorflow::VariantDeviceCopyDirection, std::type_index const&, std::function<tensorflow::Status (tensorflow::Variant const&, tensorflow::Variant*, std::function<tensorflow::Status (tensorflow::Tensor const&, tensorflow::Tensor*)>)> const&) () from /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/../libtensorflow_framework.so.1
#1  0x00007f19c9e143ee in tensorflow::variant_op_registry_fn_registration::UnaryVariantDeviceCopyRegistration<float>::UnaryVariantDeviceCopyRegistration(tensorflow::VariantDeviceCopyDirection, std::type_index const&, std::function<tensorflow::Status (float const&, float*, std::function<tensorflow::Status (tensorflow::Tensor const&, tensorflow::Tensor*)>)> const&) ()
   from /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/../libtensorflow_framework.so.1
#2  0x00007f19c9b6dadd in __static_initialization_and_destruction_0(int, int) [clone .constprop.306] ()
   from /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/../libtensorflow_framework.so.1
#3  0x00007f19e88f895a in ?? () from /lib64/ld-linux-x86-64.so.2
#4  0x00007f19e88f8a59 in ?? () from /lib64/ld-linux-x86-64.so.2
#5  0x00007f19e88fccbc in ?? () from /lib64/ld-linux-x86-64.so.2
#6  0x00007f19e88555cf in __GI__dl_catch_exception (exception=<optimized out>, operate=<optimized out>, args=<optimized out>)
    at dl-error-skeleton.c:196
#7  0x00007f19e88fc2a6 in ?? () from /lib64/ld-linux-x86-64.so.2
#8  0x00007f19e86d1256 in dlopen_doit (a=a@entry=0x7fffb6461940) at dlopen.c:66
#9  0x00007f19e88555cf in __GI__dl_catch_exception (exception=exception@entry=0x7fffb64618e0, operate=<optimized out>, args=<optimized out>)
    at dl-error-skeleton.c:196
#10 0x00007f19e885565f in __GI__dl_catch_error (objname=0x157a530, errstring=0x157a538, mallocedp=0x157a528, operate=<optimized out>, 
    args=<optimized out>) at dl-error-skeleton.c:215
#11 0x00007f19e86d1a25 in _dlerror_run (operate=operate@entry=0x7f19e86d1200 <dlopen_doit>, args=args@entry=0x7fffb6461940) at dlerror.c:163
#12 0x00007f19e86d12e6 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#13 0x000000000062c750 in _PyImport_FindSharedFuncptr ()
#14 0x0000000000636e58 in _PyImport_LoadDynamicModuleWithSpec ()
#15 0x000000000063713f in ?? ()
#16 0x00000000005d80e7 in _PyMethodDef_RawFastCallDict ()
#17 0x00000000005d82aa in PyCFunction_Call ()
#18 0x0000000000553064 in _PyEval_EvalFrameDefault ()
#19 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#20 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#21 0x000000000054afe0 in ?? ()
#22 0x000000000055211b in _PyEval_EvalFrameDefault ()
#23 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#24 0x000000000054e3ac in _PyEval_EvalFrameDefault ()
#25 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#26 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#27 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#28 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#29 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#30 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#31 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#32 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#33 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#34 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#35 0x000000000054afe0 in ?? ()
#36 0x000000000055211b in _PyEval_EvalFrameDefault ()
#37 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#38 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#39 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#40 0x0000000000558a0e in ?? ()
#41 0x00000000005d80e7 in _PyMethodDef_RawFastCallDict ()
#42 0x00000000005d82aa in PyCFunction_Call ()
#43 0x0000000000553064 in _PyEval_EvalFrameDefault ()
#44 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#45 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#46 0x000000000054afe0 in ?? ()
#47 0x000000000055211b in _PyEval_EvalFrameDefault ()
#48 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#49 0x000000000054e3ac in _PyEval_EvalFrameDefault ()
#50 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#51 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#52 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#53 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#54 0x00000000005d9906 in _PyFunction_FastCallDict ()
#55 0x00000000005db0f4 in ?? ()
#56 0x00000000005db55d in _PyObject_CallMethodIdObjArgs ()
#57 0x000000000053a87b in PyImport_ImportModuleLevelObject ()
#58 0x0000000000550059 in _PyEval_EvalFrameDefault ()
#59 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#60 0x0000000000558a0e in ?? ()
#61 0x00000000005d80e7 in _PyMethodDef_RawFastCallDict ()
#62 0x00000000005d82aa in PyCFunction_Call ()
#63 0x0000000000553064 in _PyEval_EvalFrameDefault ()
#64 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#65 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#66 0x000000000054afe0 in ?? ()
#67 0x000000000055211b in _PyEval_EvalFrameDefault ()
#68 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#69 0x000000000054e3ac in _PyEval_EvalFrameDefault ()
#70 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#71 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#72 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#73 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#74 0x00000000005d9906 in _PyFunction_FastCallDict ()
#75 0x00000000005db0f4 in ?? ()
#76 0x00000000005db55d in _PyObject_CallMethodIdObjArgs ()
#77 0x000000000053a87b in PyImport_ImportModuleLevelObject ()
#78 0x0000000000556774 in ?? ()
#79 0x00000000005d831a in PyCFunction_Call ()
#80 0x0000000000553064 in _PyEval_EvalFrameDefault ()
#81 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#82 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#83 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#84 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#85 0x00000000005d9ace in _PyFunction_FastCallDict ()
#86 0x00000000005db0f4 in ?? ()
#87 0x00000000005db55d in _PyObject_CallMethodIdObjArgs ()
#88 0x000000000053a7a3 in PyImport_ImportModuleLevelObject ()
#89 0x0000000000550059 in _PyEval_EvalFrameDefault ()
#90 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#91 0x0000000000558a0e in ?? ()
#92 0x00000000005d80e7 in _PyMethodDef_RawFastCallDict ()
#93 0x00000000005d82aa in PyCFunction_Call ()
#94 0x0000000000553064 in _PyEval_EvalFrameDefault ()
#95 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#96 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#97 0x000000000054afe0 in ?? ()
#98 0x000000000055211b in _PyEval_EvalFrameDefault ()
#99 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#100 0x000000000054e3ac in _PyEval_EvalFrameDefault ()
#101 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#102 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#103 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#104 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#105 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#106 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#107 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#108 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#109 0x000000000054afe0 in ?? ()
#110 0x000000000055211b in _PyEval_EvalFrameDefault ()
#111 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#112 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#113 0x000000000054afe0 in ?? ()
#114 0x000000000055211b in _PyEval_EvalFrameDefault ()
#115 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#116 0x000000000054afe0 in ?? ()
#117 0x000000000055211b in _PyEval_EvalFrameDefault ()
#118 0x00000000005d9906 in _PyFunction_FastCallDict ()
#119 0x00000000004d9f62 in ?? ()
#120 0x00000000005db202 in ?? ()
#121 0x00000000005db499 in PyObject_CallFunctionObjArgs ()
#122 0x0000000000589bbb in ?? ()
#123 0x00000000005918be in ?? ()
#124 0x000000000055747e in ?? ()
#125 0x00000000005d7c03 in _PyMethodDef_RawFastCallKeywords ()
#126 0x0000000000551fc3 in _PyEval_EvalFrameDefault ()
#127 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#128 0x00000000005d9ace in _PyFunction_FastCallDict ()
#129 0x00000000005db0f4 in ?? ()
#130 0x00000000005db55d in _PyObject_CallMethodIdObjArgs ()
#131 0x000000000053a7a3 in PyImport_ImportModuleLevelObject ()
#132 0x0000000000550059 in _PyEval_EvalFrameDefault ()
#133 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#134 0x0000000000558a0e in ?? ()
#135 0x00000000005d80e7 in _PyMethodDef_RawFastCallDict ()
#136 0x00000000005d82aa in PyCFunction_Call ()
#137 0x0000000000553064 in _PyEval_EvalFrameDefault ()
#138 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#139 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#140 0x000000000054afe0 in ?? ()
#141 0x000000000055211b in _PyEval_EvalFrameDefault ()
#142 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#143 0x000000000054e3ac in _PyEval_EvalFrameDefault ()
#144 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#145 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#146 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#147 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#148 0x00000000005d9906 in _PyFunction_FastCallDict ()
#149 0x00000000005db0f4 in ?? ()
#150 0x00000000005db55d in _PyObject_CallMethodIdObjArgs ()
#151 0x000000000053a87b in PyImport_ImportModuleLevelObject ()
#152 0x0000000000550059 in _PyEval_EvalFrameDefault ()
#153 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#154 0x0000000000558a0e in ?? ()
#155 0x00000000005d80e7 in _PyMethodDef_RawFastCallDict ()
#156 0x00000000005d82aa in PyCFunction_Call ()
#157 0x0000000000553064 in _PyEval_EvalFrameDefault ()
#158 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#159 0x00000000005d88c2 in _PyFunction_FastCallKeywords ()
#160 0x000000000054afe0 in ?? ()
#161 0x000000000055211b in _PyEval_EvalFrameDefault ()
#162 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#163 0x000000000054e3ac in _PyEval_EvalFrameDefault ()
#164 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#165 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#166 0x00000000005d85cc in _PyFunction_FastCallKeywords ()
#167 0x000000000054e210 in _PyEval_EvalFrameDefault ()
#168 0x00000000005d9906 in _PyFunction_FastCallDict ()
#169 0x00000000005db0f4 in ?? ()
#170 0x00000000005db55d in _PyObject_CallMethodIdObjArgs ()
#171 0x000000000053a87b in PyImport_ImportModuleLevelObject ()
#172 0x0000000000550059 in _PyEval_EvalFrameDefault ()
#173 0x000000000054baa2 in _PyEval_EvalCodeWithName ()
#174 0x000000000054dd03 in PyEval_EvalCode ()
#175 0x0000000000630d02 in ?? ()
#176 0x0000000000480d74 in ?? ()
#177 0x0000000000480ef6 in PyRun_InteractiveLoopFlags ()
#178 0x0000000000631c13 in PyRun_AnyFileExFlags ()
#179 0x00000000006541ce in ?? ()
#180 0x000000000065452e in _Py_UnixMain ()
#181 0x00007f19e871db6b in __libc_start_main (main=0x4bcb00 <main>, argc=1, argv=0x7fffb6469058, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffb6469048) at ../csu/libc-start.c:308
#182 0x00000000005e01aa in _start ()
```

**Comment by justin1121** [comment]
Noticed something similar on a macos version in circleci. Are you running on macos also?

**Comment by youben11** [comment]
Nope, running on Linux, since the environment is the same using the Docker image, my guess is that  this is either an OS or a CPU level problem.

**Comment by justin1121** [comment]
Yeah pretty crazy. There's some issues still with running c++17 software I believe and tensorflow definitely isn't thoroughly tested with c++17. They're looking in to building tensorflow with c++14 soon and SEAL can be built with c++14 as well. So hopefully we won't need to use a custom build and can avoid these kind of errors.

**Comment by mortendahl** [comment]
Okay to close this one?

**Comment by mortendahl** [comment]
Closing for now. Happy to re-open as needed.
