### ISSUE TITLE
importing tf-seal ends with 'GLIBC_2.29' not found error

### ISSUE THREAD

**Issue by Netanel-f** [tf-encrypted/tf-seal#62]
OS: Ubuntu 18.04.4
I have installed tf-seal with both binary custom tensorflow and with locally compiled version, on two virtual environments, using Python's virtualenv and conda.
All scenerios installed the library successfully but when importing tf_seal it throws NotFoundError:
```>> import tf_seal as tfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pipoc/anaconda3/envs/HE-cenv2/lib/python3.7/site-packages/tf_seal/__init__.py", line 1, in <module>
    from tf_seal.python.tensor import constant
  File "/home/pipoc/anaconda3/envs/HE-cenv2/lib/python3.7/site-packages/tf_seal/python/tensor.py", line 4, in <module>
    import tf_seal.python.ops.seal_ops as ops
  File "/home/pipoc/anaconda3/envs/HE-cenv2/lib/python3.7/site-packages/tf_seal/python/ops/seal_ops.py", line 5, in <module>
    seal_ops = load_library.load_op_library(op_lib_file)
  File "/home/pipoc/anaconda3/envs/HE-cenv2/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/pipoc/anaconda3/envs/HE-cenv2/lib/python3.7/site-packages/tf_seal/python/ops/_seal_ops.so)```

**Comment by mortendahl** [comment]
Hi @Netanel-f, any chance it could be something similar to this: https://forum.juce.com/t/glibc-2-29-not-found-on-ubuntu-18-04/34960/9 ?

**Comment by r-kellerm** [comment]
Hi,

I have the same issue - Python3.7 virtualenv, (Not Conda).
When compiling the custom TF from sources (assuming branch c++17), I can't import tensorflow: 

> module 'tensorflow' has no attribute 'compat'

When installing the pre-built binary, I get the same error as @Netanel-f , but the complaint is on another version -

>  version `GLIBC_2.28' not found

P.S. I'm running on an Azure Ubuntu 18.04 _VM_ in case it matters (uname -r: 5.0.0-1036-azure, lsb_release: Ubuntu 18.04.4 LTS).

@mortendahl - as for the issue you refer to, if I understand it correctly this is about x86/ x64 mismatch, right? I tried to verify the installations - looks like all the packages are properly x86_x64. I verified and this is also the actual architecture.

Thank you!

**Comment by andreamil93** [comment]
I have the same issue. Have you guys solved it?

**Comment by KimiakiShirahama** [comment]
I also have the same issue on Ubuntu 18.04. I really want to use tf-seal...

As far as I knew, this error is related to the version of c++. I would like to know the exact system requirements to run tf-seal.

**Comment by Wixee** [comment]
https://github.com/howard1005/u18_tf_seal/tree/8138587caeaa42384e9038711b167e8a51efca08
Thanks to @howard1005, we can just install two whl files in order to use tf_seal.

**Comment by KimiakiShirahama** [comment]
@Wixee 
Thank you so much!!! By install the custom tensoflow and tf-seal you provided, I could successfully run tf-seal on my Ubuntu 18.04!!!
